notifications:
  email: false

sudo: required

language: python

cache:
  directories:
    - $HOME/.cache/docker
    - $HOME/.cache/pip

python:
  - "3.7.4"

before_install:
  - docker-compose build
  - docker-compose up -d

script:
  - docker-compose ps